version: "2.0"
services:
  nginx:
    build:
      context: "./balance/"
    ports:
      - "80:80"
    networks:
      - frontend
  iotnode:
    build:
      context: "./iotnode"
    ports:
      - 5000/TCP
    depends_on:
      - nginx
    networks:
      frontend:
        aliases:
         - web_worker
    privileged: true
    environment:
      - "affinity:container!=pizerodockerdemo_iotnode_*"

networks:
  frontend:
    driver: overlay
