version: "2.0"
services:
  balance:
    build:
      context: "./balance/"
    ports:
     - "80:80"
    networks:
      - frontend

  iot_node:
    build:
      context: "./iotnode"
    ports:
     - 5000/TCP    
    depends_on:
      - balance
    privileged: true
    networks:
      frontend:
        aliases:
          - iot_worker
      backend:       
        aliases:
          - web_worker_backend

networks:  
  frontend:
    driver: bridge
  backend:
    driver: bridge
